#!/bin/bash


url=$1
test $url || {
  echo "Usage: $0 url"
}

# prep for loop
tmp_file='/tmp/.auto-paginate-cache'
next_page_url="$url"
test -t 1 || in_pipeline=true

function trim_trailing_ws() {
  sed 's/	/  /g'   | # tabs to spaces
  sed 's/[ ]*$//g' | # trailing space to nothing
  sed 's/*$//g'    # remove weird trailing return char
}

function trim_blank_lines() {
  grep -v ^$
}

function trim_response_to_headers() {
  # multiline match
  #   first separating blank line (separation of headers and body)
  # through
  #   any line (the rest of the file)
  # then delete them
  sed -e '/^$/,/$./d'
}

function trim_response_to_body() {
  # multiline match
  #   http response code line (first line)
  # through
  #   first separating blank line, which might contain a CR (^M), (the separation of headers and body)
  # then delete them
  sed -E -e '/(^HTTP|^http)/,/^$/d'
}

function link_header_from_response() {
  trim_response_to_headers |
  grep '^Link:'
}

function named_link_from_link_header() {
  local name=$1

  tr , '\n'            |  # turn commas into newlines
  grep 'rel="'$name'"' |  # stop without a "next" link
  sed 's/^$//g'        |  # omit blank lines
  sed -E 's/(Link:|<|>|;|rel="'$name'")//g'  # trim to only the link
}

function get_next_page_url() {
  cat $tmp_file             |
  link_header_from_response |
  named_link_from_link_header "next"
}

function get_named_link_header() {
  cat $tmp_file             |
  link_header_from_response |
  named_link_from_link_header "last"
}

function stderrcho() {
  >&2 echo "$@"
}

function monitor_if_in_pipeline() {
  test -n "$in_pipeline" && {
    stderrcho "$next_page_url / $(get_named_link_header)"
  }
}

# http://tools.ietf.org/html/rfc4627#section-1.1
# legal padding whitespace characters:
#   %x20 Space
#   %x09 Horizontal tab
#   %x0A Line feed or New line
#   %x0D Carriage return
# TODO all of these are replaced with spaces before strip functions are called

function strip_leading_begin_array_character() {
  sed -E '1s/^[ ]*[\[]?//'
  # remove zero or more spaces and zero to one [ beginine the first line
}

function strip_trailing_end_array_character() {
  sed -E '1s/]?[ ]*$//'
  # remove zero to one ] and zero or more spaces followed by an end of line
}

function strip_parent_array_brackets() {
  strip_leading_begin_array_character |
  tail -r | # reverse line order, so we can play with only the first one
  strip_trailing_end_array_character |
  tail -r   # reverse line order, so they are in normal order again
}

# emit array begin
echo '['

while true; do
# curl next page
# -s silence download time
# -i provide headers
# include options (e.g. Authentication headers)
# stuff it in a tmp file
  monitor_if_in_pipeline
  curl $next_page_url -s -i "${@:2}" > $tmp_file
  next_page_url=$(get_next_page_url)

#  cat $tmp_file  | json -H        # strip headers and spit out json
  cat $tmp_file |
  trim_trailing_ws |
  trim_response_to_body |
  trim_trailing_ws |
  trim_blank_lines |
   strip_parent_array_brackets

  test -n "$next_page_url" || break   # break if this was the last page

  # emit array value separator
  echo ','

done #| json -g                    # concat arrays

# emit array end
echo ']'

rm $tmp_file
